### ISSUE TITLE
TypeError時に適切なエラーメッセージを表示する

### ISSUE THREAD

**Issue by Ancient-Scapes** [Ancient-Scapes/discord-chatgpt-bot#1]
原因が不明、APIのタイムアウト？

**Comment by Ancient-Scapes** [comment]
```
TypeError: Cannot read properties of undefined (reading '0')
    at chatCompletion (/Users/r_sato/project/other/discord-go-bot/chatgpt.ts:30:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (/Users/r_sato/project/other/discord-go-bot/index.ts:21:18)
```
chices[0]がとれていない

**Comment by Ancient-Scapes** [comment]
https://github.com/Ancient-Scapes/discord-chatgpt-bot/commit/de6378f0eab925ec4bc342e06623b726cc04ce59

ここらへんでやった
JSON.stringfyでまとめて返す
